version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    binary: icmpx
    main: ./main.go

nfpms:
  - id: packages
    package_name: icmpx
    vendor: loresuso
    homepage: https://github.com/loresuso/icmpx
    maintainer: loresuso
    description: ICMP-based data exfiltration and reverse shell tool
    license: MIT
    formats:
      - deb
    bindir: /usr/bin
    scripts:
      postinstall: |
        #!/bin/sh
        # Add CAP_NET_RAW capability to the binary if setcap is available
        if command -v setcap >/dev/null 2>&1; then
          setcap cap_net_raw+ep /usr/bin/icmpx || echo "Warning: Failed to set capabilities. Run 'sudo setcap cap_net_raw+ep /usr/bin/icmpx' manually."
        else
          echo "Warning: setcap not found. Install libcap2-bin package and run 'sudo setcap cap_net_raw+ep /usr/bin/icmpx' to enable non-root usage."
        fi

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  github:
    owner: loresuso
    name: icmpx
